package parcial1.vista;

import java.awt.*;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import parcial1.modelo.Ecosistema;
import parcial1.modelo.Entidad;
import parcial1.modelo.Planta;
import parcial1.modelo.Conejo;
import parcial1.modelo.Lobo;

public class PanelReporte extends javax.swing.JFrame {

    public PanelReporte(Ecosistema eco, String causaFin) {
        initComponents();
        cargarDatos(eco, causaFin);
        setLocationRelativeTo(null);
    }

    private void cargarDatos(Ecosistema eco, String causaFin) {
        if (eco == null) return;

        // 1. Cargar Datos del Resumen
        lblCausaVal.setText(causaFin);
        lblTurnosVal.setText(String.valueOf(eco.getTurnoActual() - 1));
        lblActividadVal.setText("Turno " + eco.getTurnoMayorActividad() + " (" + eco.getMaxEventos() + " eventos)");

        // Longevas
        Planta pLongeva = null; Conejo cLongevo = null; Lobo lLongevo = null;
        for (Planta p : eco.getPlantas()) if (pLongeva == null || p.getEdad() > pLongeva.getEdad()) pLongeva = p;
        for (Conejo c : eco.getConejos()) if (cLongevo == null || c.getEdad() > cLongevo.getEdad()) cLongevo = c;
        for (Lobo l : eco.getLobos()) if (lLongevo == null || l.getEdad() > lLongevo.getEdad()) lLongevo = l;

        lblPlantaVal.setText(pLongeva != null ? pLongeva.getNombre() + " (" + pLongeva.getEdad() + " años)" : "N/A");
        lblConejoVal.setText(cLongevo != null ? cLongevo.getNombre() + " (" + cLongevo.getEdad() + " años)" : "N/A");
        lblLoboVal.setText(lLongevo != null ? lLongevo.getNombre() + " (" + lLongevo.getEdad() + " años)" : "N/A");

        // Cazador
        Lobo mejorLobo = null;
        for (Lobo l : eco.getLobos()) {
            if (mejorLobo == null || l.getExitosCaza() > mejorLobo.getExitosCaza()) mejorLobo = l;
        }
        lblCazadorVal.setText(mejorLobo != null ? mejorLobo.getNombre() + " (" + mejorLobo.getExitosCaza() + " cazas)" : "N/A");

        // Estadísticas agregadas
        String statString = String.format("<html>"
            + "🌿 Plantas: Nacimientos: %d, Muertes: %d<br>"
            + "🐰 Conejos: Nacimientos: %d, Muertes: %d<br>"
            + "🐺 Lobos: Nacimientos: %d, Muertes: %d</html>",
            eco.getNacimientosPlantas(), eco.getMuertesPlantas(),
            eco.getNacimientosConejos(), eco.getMuertesConejos(),
            eco.getNacimientosLobos(), eco.getMuertesLobos()
        );
        lblStatsVal.setText(statString);

        // 2. Cargar Historial y Extremos
        String[] colHistorial = {"Turno", "Plantas", "Conejos", "Lobos"};
        DefaultTableModel modelHistorial = new DefaultTableModel(colHistorial, 0) {
            @Override
            public boolean isCellEditable(int r, int c) { return false; }
        };
        tblHistorial.setModel(modelHistorial);

        ArrayList<Integer> hP = eco.getHistorialPlantas();
        ArrayList<Integer> hC = eco.getHistorialConejos();
        ArrayList<Integer> hL = eco.getHistorialLobos();

        int n = hP.size();
        for (int i = 0; i < n; i++) {
            Object[] row = {
                "Turno " + i + (i == 0 ? " (Inicio)" : ""),
                hP.get(i),
                hC.get(i),
                hL.get(i)
            };
            modelHistorial.addRow(row);
        }

        // Calcular extremos
        int maxP = -1, minP = Integer.MAX_VALUE, tMaxP = 0, tMinP = 0;
        int maxC = -1, minC = Integer.MAX_VALUE, tMaxC = 0, tMinC = 0;
        int maxL = -1, minL = Integer.MAX_VALUE, tMaxL = 0, tMinL = 0;

        for (int i = 0; i < n; i++) {
            int valP = hP.get(i);
            if (valP > maxP) { maxP = valP; tMaxP = i; }
            if (valP < minP) { minP = valP; tMinP = i; }

            int valC = hC.get(i);
            if (valC > maxC) { maxC = valC; tMaxC = i; }
            if (valC < minC) { minC = valC; tMinC = i; }

            int valL = hL.get(i);
            if (valL > maxL) { maxL = valL; tMaxL = i; }
            if (valL < minL) { minL = valL; tMinL = i; }
        }

        lblExtPlantas.setText(String.format("🌿 Plantas: Máximo %d (Turno %d) | Mínimo %d (Turno %d)", maxP, tMaxP, minP, tMinP));
        lblExtConejos.setText(String.format("🐰 Conejos: Máximo %d (Turno %d) | Mínimo %d (Turno %d)", maxC, tMaxC, minC, tMinC));
        lblExtLobos.setText(String.format("🐺 Lobos:   Máximo %d (Turno %d) | Mínimo %d (Turno %d)", maxL, tMaxL, minL, tMinL));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();
        tabbedPane = new javax.swing.JTabbedPane();
        pnlResumen = new javax.swing.JPanel();
        lblTituloResumen = new javax.swing.JLabel();
        pnlCuerpoResumen = new javax.swing.JPanel();
        lblCausaTitle = new javax.swing.JLabel();
        lblCausaVal = new javax.swing.JLabel();
        lblTurnosTitle = new javax.swing.JLabel();
        lblTurnosVal = new javax.swing.JLabel();
        lblActividadTitle = new javax.swing.JLabel();
        lblActividadVal = new javax.swing.JLabel();
        lblPlantaTitle = new javax.swing.JLabel();
        lblPlantaVal = new javax.swing.JLabel();
        lblConejoTitle = new javax.swing.JLabel();
        lblConejoVal = new javax.swing.JLabel();
        lblLoboTitle = new javax.swing.JLabel();
        lblLoboVal = new javax.swing.JLabel();
        lblCazadorTitle = new javax.swing.JLabel();
        lblCazadorVal = new javax.swing.JLabel();
        lblStatsTitle = new javax.swing.JLabel();
        lblStatsVal = new javax.swing.JLabel();
        pnlEstadisticas = new javax.swing.JPanel();
        scrollHistorial = new javax.swing.JScrollPane();
        tblHistorial = new javax.swing.JTable();
        pnlExtremos = new javax.swing.JPanel();
        lblExtPlantas = new javax.swing.JLabel();
        lblExtConejos = new javax.swing.JLabel();
        lblExtLobos = new javax.swing.JLabel();
        pnlBoton = new javax.swing.JPanel();
        btnCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Reporte Final del Ecosistema 📊");

        pnlMain.setBackground(new java.awt.Color(255, 255, 255));
        pnlMain.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        pnlMain.setLayout(new java.awt.BorderLayout(0, 10));

        tabbedPane.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N

        pnlResumen.setBackground(new java.awt.Color(255, 255, 255));
        pnlResumen.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15));
        pnlResumen.setLayout(new java.awt.BorderLayout(0, 10));

        lblTituloResumen.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        lblTituloResumen.setForeground(new java.awt.Color(17, 24, 39));
        lblTituloResumen.setText("Resumen de Simulación");
        pnlResumen.add(lblTituloResumen, java.awt.BorderLayout.NORTH);

        pnlCuerpoResumen.setBackground(new java.awt.Color(255, 255, 255));
        pnlCuerpoResumen.setLayout(new java.awt.GridLayout(8, 2, 10, 10));

        lblCausaTitle.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lblCausaTitle.setText("Causa de finalización:");
        pnlCuerpoResumen.add(lblCausaTitle);

        lblCausaVal.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        lblCausaVal.setText("Causa");
        pnlCuerpoResumen.add(lblCausaVal);

        lblTurnosTitle.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lblTurnosTitle.setText("Total de turnos ejecutados:");
        pnlCuerpoResumen.add(lblTurnosTitle);

        lblTurnosVal.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        lblTurnosVal.setText("0");
        pnlCuerpoResumen.add(lblTurnosVal);

        lblActividadTitle.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lblActividadTitle.setText("Turno con mayor actividad:");
        pnlCuerpoResumen.add(lblActividadTitle);

        lblActividadVal.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        lblActividadVal.setText("Turno X");
        pnlCuerpoResumen.add(lblActividadVal);

        lblPlantaTitle.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lblPlantaTitle.setText("Planta más longeva:");
        pnlCuerpoResumen.add(lblPlantaTitle);

        lblPlantaVal.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        lblPlantaVal.setText("Planta");
        pnlCuerpoResumen.add(lblPlantaVal);

        lblConejoTitle.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lblConejoTitle.setText("Conejo más longevo:");
        pnlCuerpoResumen.add(lblConejoTitle);

        lblConejoVal.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        lblConejoVal.setText("Conejo");
        pnlCuerpoResumen.add(lblConejoVal);

        lblLoboTitle.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lblLoboTitle.setText("Lobo más longevo:");
        pnlCuerpoResumen.add(lblLoboTitle);

        lblLoboVal.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        lblLoboVal.setText("Lobo");
        pnlCuerpoResumen.add(lblLoboVal);

        lblCazadorTitle.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lblCazadorTitle.setText("Lobo más cazador:");
        pnlCuerpoResumen.add(lblCazadorTitle);

        lblCazadorVal.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        lblCazadorVal.setText("Lobo");
        pnlCuerpoResumen.add(lblCazadorVal);

        lblStatsTitle.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lblStatsTitle.setText("Estadísticas totales (Nac/Muer):");
        pnlCuerpoResumen.add(lblStatsTitle);

        lblStatsVal.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        lblStatsVal.setText("Stats");
        pnlCuerpoResumen.add(lblStatsVal);

        pnlResumen.add(pnlCuerpoResumen, java.awt.BorderLayout.CENTER);

        tabbedPane.addTab("Resumen General 📋", pnlResumen);

        pnlEstadisticas.setBackground(new java.awt.Color(255, 255, 255));
        pnlEstadisticas.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15));
        pnlEstadisticas.setLayout(new java.awt.BorderLayout(0, 10));

        scrollHistorial.setViewportView(tblHistorial);

        pnlEstadisticas.add(scrollHistorial, java.awt.BorderLayout.CENTER);

        pnlExtremos.setBackground(new java.awt.Color(255, 255, 255));
        pnlExtremos.setBorder(javax.swing.BorderFactory.createTitledBorder("Mínimos y Máximos Históricos"));
        pnlExtremos.setLayout(new java.awt.GridLayout(3, 1, 0, 5));

        lblExtPlantas.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        lblExtPlantas.setText("Plantas:");
        pnlExtremos.add(lblExtPlantas);

        lblExtConejos.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        lblExtConejos.setText("Conejos:");
        pnlExtremos.add(lblExtConejos);

        lblExtLobos.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        lblExtLobos.setText("Lobos:");
        pnlExtremos.add(lblExtLobos);

        pnlEstadisticas.add(pnlExtremos, java.awt.BorderLayout.SOUTH);

        tabbedPane.addTab("Historial y Extremos 📈", pnlEstadisticas);

        pnlMain.add(tabbedPane, java.awt.BorderLayout.CENTER);

        pnlBoton.setBackground(new java.awt.Color(243, 244, 246));
        pnlBoton.setLayout(new java.awt.FlowLayout());

        btnCerrar.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnCerrar.setText("Cerrar y Volver al Menú 🔄");
        pnlBoton.add(btnCerrar);

        pnlMain.add(pnlBoton, java.awt.BorderLayout.SOUTH);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCerrar;
    public javax.swing.JLabel lblActividadTitle;
    public javax.swing.JLabel lblActividadVal;
    public javax.swing.JLabel lblCausaTitle;
    public javax.swing.JLabel lblCausaVal;
    public javax.swing.JLabel lblCazadorTitle;
    public javax.swing.JLabel lblCazadorVal;
    public javax.swing.JLabel lblConejoTitle;
    public javax.swing.JLabel lblConejoVal;
    public javax.swing.JLabel lblExtConejos;
    public javax.swing.JLabel lblExtLobos;
    public javax.swing.JLabel lblExtPlantas;
    public javax.swing.JLabel lblLoboTitle;
    public javax.swing.JLabel lblLoboVal;
    public javax.swing.JLabel lblPlantaTitle;
    public javax.swing.JLabel lblPlantaVal;
    public javax.swing.JLabel lblStatsTitle;
    public javax.swing.JLabel lblStatsVal;
    public javax.swing.JLabel lblTituloResumen;
    public javax.swing.JLabel lblTurnosTitle;
    public javax.swing.JLabel lblTurnosVal;
    public javax.swing.JPanel pnlBoton;
    public javax.swing.JPanel pnlCuerpoResumen;
    public javax.swing.JPanel pnlEstadisticas;
    public javax.swing.JPanel pnlExtremos;
    public javax.swing.JPanel pnlMain;
    public javax.swing.JPanel pnlResumen;
    public javax.swing.JScrollPane scrollHistorial;
    public javax.swing.JTabbedPane tabbedPane;
    public javax.swing.JTable tblHistorial;
    // End of variables declaration//GEN-END:variables
}
