package parcial1.vista;

import java.awt.*;
import javax.swing.*;
import parcial1.modelo.Clima;

public class PantallaSimulador extends javax.swing.JFrame {

    public PantallaSimulador() {
        initComponents();
        
        // Llenar el ComboBox del clima
        cmbClima.setModel(new javax.swing.DefaultComboBoxModel<>(Clima.values()));
        
        // Centrar ventana
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlConfig = new javax.swing.JPanel();
        lblConfigTitle = new javax.swing.JLabel();
        containerPanel = new javax.swing.JPanel();
        formPanel = new javax.swing.JPanel();
        lblPlantas = new javax.swing.JLabel();
        spnPlantas = new javax.swing.JSpinner();
        lblConejos = new javax.swing.JLabel();
        spnConejos = new javax.swing.JSpinner();
        lblLobos = new javax.swing.JLabel();
        spnLobos = new javax.swing.JSpinner();
        lblClima = new javax.swing.JLabel();
        cmbClima = new javax.swing.JComboBox();
        lblTurnos = new javax.swing.JLabel();
        spnTurnos = new javax.swing.JSpinner();
        buttonsPanel = new javax.swing.JPanel();
        btnIniciarSim = new javax.swing.JButton();
        btnCargarSim = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Configuración del Ecosistema 🌿");

        pnlConfig.setBackground(new java.awt.Color(243, 244, 246));
        pnlConfig.setLayout(new java.awt.GridBagLayout());

        lblConfigTitle.setFont(new java.awt.Font("SansSerif", 1, 22)); // NOI18N
        lblConfigTitle.setForeground(new java.awt.Color(17, 24, 39));
        lblConfigTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblConfigTitle.setText("SIMULADOR DE ECOSISTEMA");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 0);
        pnlConfig.add(lblConfigTitle, gridBagConstraints);

        containerPanel.setBackground(new java.awt.Color(255, 255, 255));
        containerPanel.setLayout(new java.awt.BorderLayout(0, 20));

        formPanel.setBackground(new java.awt.Color(255, 255, 255));
        formPanel.setLayout(new java.awt.GridLayout(5, 2, 15, 15));

        lblPlantas.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        lblPlantas.setForeground(new java.awt.Color(55, 65, 81));
        lblPlantas.setText("Plantas iniciales (5-30):");
        formPanel.add(lblPlantas);

        spnPlantas.setModel(new javax.swing.SpinnerNumberModel(10, 5, 30, 1));
        formPanel.add(spnPlantas);

        lblConejos.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        lblConejos.setForeground(new java.awt.Color(55, 65, 81));
        lblConejos.setText("Conejos iniciales (2-15):");
        formPanel.add(lblConejos);

        spnConejos.setModel(new javax.swing.SpinnerNumberModel(5, 2, 15, 1));
        formPanel.add(spnConejos);

        lblLobos.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        lblLobos.setForeground(new java.awt.Color(55, 65, 81));
        lblLobos.setText("Lobos iniciales (1-5):");
        formPanel.add(lblLobos);

        spnLobos.setModel(new javax.swing.SpinnerNumberModel(2, 1, 5, 1));
        formPanel.add(spnLobos);

        lblClima.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        lblClima.setForeground(new java.awt.Color(55, 65, 81));
        lblClima.setText("Clima inicial:");
        formPanel.add(lblClima);
        formPanel.add(cmbClima);

        lblTurnos.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        lblTurnos.setForeground(new java.awt.Color(55, 65, 81));
        lblTurnos.setText("Cantidad de turnos (10-50):");
        formPanel.add(lblTurnos);

        spnTurnos.setModel(new javax.swing.SpinnerNumberModel(20, 10, 50, 1));
        formPanel.add(spnTurnos);

        containerPanel.add(formPanel, java.awt.BorderLayout.CENTER);

        buttonsPanel.setBackground(new java.awt.Color(255, 255, 255));
        buttonsPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 15, 0));

        btnIniciarSim.setBackground(new java.awt.Color(16, 185, 129));
        btnIniciarSim.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        btnIniciarSim.setForeground(new java.awt.Color(102, 255, 255));
        btnIniciarSim.setText("Iniciar Simulación 🚀");
        btnIniciarSim.setFocusPainted(false);
        btnIniciarSim.setPreferredSize(new java.awt.Dimension(210, 35));
        buttonsPanel.add(btnIniciarSim);

        btnCargarSim.setBackground(new java.awt.Color(59, 130, 246));
        btnCargarSim.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        btnCargarSim.setForeground(new java.awt.Color(0, 51, 204));
        btnCargarSim.setText("Cargar Partida Guardada 📂");
        btnCargarSim.setFocusPainted(false);
        btnCargarSim.setPreferredSize(new java.awt.Dimension(210, 35));
        buttonsPanel.add(btnCargarSim);

        containerPanel.add(buttonsPanel, java.awt.BorderLayout.SOUTH);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        pnlConfig.add(containerPanel, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlConfig, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlConfig, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCargarSim;
    public javax.swing.JButton btnIniciarSim;
    public javax.swing.JPanel buttonsPanel;
    public javax.swing.JComboBox cmbClima;
    public javax.swing.JPanel containerPanel;
    public javax.swing.JPanel formPanel;
    public javax.swing.JLabel lblClima;
    public javax.swing.JLabel lblConejos;
    public javax.swing.JLabel lblConfigTitle;
    public javax.swing.JLabel lblLobos;
    public javax.swing.JLabel lblPlantas;
    public javax.swing.JLabel lblTurnos;
    public javax.swing.JPanel pnlConfig;
    public javax.swing.JSpinner spnConejos;
    public javax.swing.JSpinner spnLobos;
    public javax.swing.JSpinner spnPlantas;
    public javax.swing.JSpinner spnTurnos;
    // End of variables declaration//GEN-END:variables
}
