/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Usuario
 */
public class ConfiguracionEcosistema extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ConfiguracionEcosistema.class.getName());

    /**
     * Creates new form ConfiguracionEcosistema
     */
    public ConfiguracionEcosistema() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPConfiguracionEcosistena = new javax.swing.JPanel();
        jlblConfiguracionEcosistema = new javax.swing.JLabel();
        jSLobos = new javax.swing.JSlider();
        jSConejos = new javax.swing.JSlider();
        jSPlantas = new javax.swing.JSlider();
        jlblClima = new javax.swing.JLabel();
        jtbSoleado = new javax.swing.JToggleButton();
        jtbLluvioso = new javax.swing.JToggleButton();
        jtbNevado = new javax.swing.JToggleButton();
        jbtnIniciarSimulacion = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Configuracion del Ecosistema");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPConfiguracionEcosistena.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlblConfiguracionEcosistema.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        jlblConfiguracionEcosistema.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblConfiguracionEcosistema.setText("Configuracion del Ecosistema");
        jPConfiguracionEcosistena.add(jlblConfiguracionEcosistema, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 39, 600, -1));

        jSLobos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPConfiguracionEcosistena.add(jSLobos, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 132, -1, -1));
        jPConfiguracionEcosistena.add(jSConejos, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 185, -1, -1));
        jPConfiguracionEcosistena.add(jSPlantas, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 232, -1, -1));

        jlblClima.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jlblClima.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblClima.setText("Clima");
        jPConfiguracionEcosistena.add(jlblClima, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 294, -1, -1));

        jtbSoleado.setText("Soleado");
        jPConfiguracionEcosistena.add(jtbSoleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 327, 115, 110));

        jtbLluvioso.setText("Lluvioso");
        jtbLluvioso.addActionListener(this::jtbLluviosoActionPerformed);
        jPConfiguracionEcosistena.add(jtbLluvioso, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 327, 115, 110));

        jtbNevado.setText("Nevado");
        jPConfiguracionEcosistena.add(jtbNevado, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 327, 115, 110));

        jbtnIniciarSimulacion.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jbtnIniciarSimulacion.setText("Iniciar Simulacion");
        jPConfiguracionEcosistena.add(jbtnIniciarSimulacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 490, 180, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPConfiguracionEcosistena, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPConfiguracionEcosistena, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtbLluviosoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbLluviosoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtbLluviosoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ConfiguracionEcosistema().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPConfiguracionEcosistena;
    private javax.swing.JSlider jSConejos;
    private javax.swing.JSlider jSLobos;
    private javax.swing.JSlider jSPlantas;
    private javax.swing.JButton jbtnIniciarSimulacion;
    private javax.swing.JLabel jlblClima;
    private javax.swing.JLabel jlblConfiguracionEcosistema;
    private javax.swing.JToggleButton jtbLluvioso;
    private javax.swing.JToggleButton jtbNevado;
    private javax.swing.JToggleButton jtbSoleado;
    // End of variables declaration//GEN-END:variables
}
